#ifndef __SHARED__
#define __SHARED__

enum ControlType {
  CONTROL_TYPE_DEBUG,
  CONTROL_TYPE_ENCODER,
  CONTROL_TYPE_BUTTON,
  CONTROL_TYPE_POSITION,
  CONTROL_TYPE_TOUCH,
  CONTROL_TYPE_DATA
};

enum DebugMessage {
  DEBUG_BOOT,
  DEBUG_RECEIVED_ADDRESS
};

#endif __SHARED__